language: node_js
sudo: false
dist: trusty
node_js:
  - "8"
  - "10"
before_install: if [[ `npm --version` != "5.8.0" ]]; then npm install -g npm@latest; npm --version; fi
matrix:
  fast_finish: true
services:
  - mongodb
script: make travis
after_success:
  - nvm version
after_script: make report
